name: Update README with Blog Posts

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allow manual runs

jobs:
  update-readme:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Fetch RSS Feed and Update README
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://pankajpramanik.com/blog/feed/"
