name: Update README with Blog Posts

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allow manual runs

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch RSS Feed and Update README
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: |
            https://pankajpramanik.com/blog/feed/
          max_post_count: 5 # Number of posts to show
